### ISSUE TITLE
Fetch details from websites

### ISSUE THREAD

**Issue by mamenjivar** [PentaTech-Inc/Media-Trackerr#10]
Since we are a movie tracker, we will be need to find a way to get necessary information from websites such as movie/show posters, duration, genres, trailers, etc.

**Comment by mamenjivar** [comment]
I'm just a little confused with what is the purpose of this feature? Will be discussing with team.

**Comment by FabianDean** [comment]
Show/movie details are fetched from TMDB's API.
Purpose of this feature is to give an overview of a show and to ensure that users will be able to find the title they are looking for.
